# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'File Manager App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'KeychainAccess'
  pod 'SnapKit', '~> 5.0.0'

  # Pods for File Manager App

end
